version: "3.3"

services:
  crossmodalgraph-gpu:
    image: 'crossmodalgraph-gpu:latest'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/Cross_modality_graph
    command: tail -f /dev/null
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia